parameters:
  eventbrite.client_class: Guzzle\Service\Client
  eventbrite.client_factory_class: SFBCN\EventbriteBundle\Eventbrite\ClientFactory
  eventbrite.base_url: "https://www.eventbrite.com/xml/"
  eventbrite.persister_class: SFBCN\EventbriteBundle\Eventbrite\Persister
  eventbrite.mapper_class: SFBCN\EventbriteBundle\Eventbrite\Mapper
  eventbrite.base_repository_class: SFBCN\EventbriteBundle\Eventbrite\AbstractRepository
  eventbrite.events_class: SFBCN\EventbriteBundle\Entity\EventRepository
  eventbrite.organizers_class: SFBCN\EventbriteBundle\Entity\OrganizerRepository
  eventbrite.venues_class: SFBCN\EventbriteBundle\Entity\VenueRepository
  eventbrite.users_class: SFBCN\EventbriteBundle\Entity\UserRepository
  eventbrite.forms.event.class: SFBCN\EventbriteBundle\Form\EventType
  eventbrite.forms.type.venue.class: SFBCN\EventbriteBundle\Form\Type\VenueType
  eventbrite.forms.choice_list.venue.class: SFBCN\EventbriteBundle\Form\ChoiceList\VenueChoiceList
  eventbrite.forms.data_transformer.venue_to_id.class: SFBCN\EventbriteBundle\Form\DataTransformer\VenueToIdTransformer
  eventbrite.forms.type.organizer.class: SFBCN\EventbriteBundle\Form\Type\OrganizerType
  eventbrite.forms.choice_list.organizer.class: SFBCN\EventbriteBundle\Form\ChoiceList\OrganizerChoiceList
  eventbrite.forms.data_transformer.organizer_to_id.class: SFBCN\EventbriteBundle\Form\DataTransformer\OrganizerToIdTransformer

services:
  eventbrite.client:
    class: %eventbrite.client_class%
    factory_class: %eventbrite.client_factory_class%
    factory_method: "factory"
    public: false
    arguments:
      [{ app_key: %app_key%, user_key: %user_key%, services_description_file: %services_description_file%, base_url: %eventbrite.base_url%}]

  eventbrite.persister:
    class: %eventbrite.persister_class%
    arguments:
      [@eventbrite.client]

  eventbrite.mapper:
    class: %eventbrite.mapper_class%

  # Forms
  eventbrite.forms.event:
    class: %eventbrite.forms.event.class%

  eventbrite.forms.choice_list.venue:
    class: %eventbrite.forms.choice_list.venue.class%
    arguments:
      [@eventbrite.users]

  eventbrite.forms.choice_list.organizer:
    class: %eventbrite.forms.choice_list.organizer.class%
    arguments:
      [@eventbrite.users]

  eventbrite.forms.data_transformer.venue_to_id:
    class: %eventbrite.forms.data_transformer.venue_to_id.class%
    arguments:
      [@eventbrite.venues]

  eventbrite.forms.data_transformer.organizer_to_id:
    class: %eventbrite.forms.data_transformer.organizer_to_id.class%
    arguments:
      [@eventbrite.organizers]

  eventbrite.forms.type.venue:
    class: %eventbrite.forms.type.venue.class%
    arguments:
      [@eventbrite.forms.choice_list.venue, @eventbrite.forms.data_transformer.venue_to_id]
    tags:
      - { name: form.type, alias: venue }

  eventbrite.forms.type.organizer:
    class: %eventbrite.forms.type.organizer.class%
    arguments:
      [@eventbrite.forms.choice_list.organizer, @eventbrite.forms.data_transformer.organizer_to_id]
    tags:
      - { name: form.type, alias: organizer }

  # Repositories
  eventbrite.abstract_repository:
    class:     %eventbrite.base_repository_class%
    abstract:  true
    public: false
    arguments:
      [@eventbrite.client, @eventbrite.mapper]

  eventbrite.events:
    class: %eventbrite.events_class%
    parent: eventbrite.abstract_repository
    public: true

  eventbrite.organizers:
    class: %eventbrite.organizers_class%
    parent: eventbrite.abstract_repository
    public: true

  eventbrite.venues:
    class: %eventbrite.venues_class%
    parent: eventbrite.abstract_repository
    public: true

  eventbrite.users:
    class: %eventbrite.users_class%
    parent: eventbrite.abstract_repository
    public: true
