parameters:
  eventbrite.client_class: Guzzle\Service\Client
  eventbrite.client_factory_class: SFBCN\EventbriteBundle\Eventbrite\ClientFactory
  eventbrite.base_url: "https://www.eventbrite.com/xml/"
  eventbrite.persister_class: SFBCN\EventbriteBundle\Eventbrite\Persister
  eventbrite.base_repository_class: SFBCN\EventbriteBundle\Eventbrite\AbstractRepository
  eventbrite.events_class: SFBCN\EventbriteBundle\Entity\EventRepository
  eventbrite.organizers_class: SFBCN\EventbriteBundle\Entity\OrganizerRepository
  eventbrite.venues_class: SFBCN\EventbriteBundle\Entity\VenueRepository
  eventbrite.users_class: SFBCN\EventbriteBundle\Entity\UserRepository

services:
  eventbrite.client:
    class: %eventbrite.client_class%
    factory_class: %eventbrite.client_factory_class%
    factory_method: "factory"
    public: false
    arguments:
      [{ app_key: %app_key%, user_key: %user_key%, services_description_file: %services_description_file%, base_url: %eventbrite.base_url%}]

  eventbrite.persister:
    class: %eventbrite.persister_class%
    arguments:
      [@eventbrite.client]

  eventbrite.mapper:
    class: %eventbrite.mapper%

  eventbrite.abstract_repository:
    class:     %eventbrite.base_repository_class%
    abstract:  true
    public: false
    arguments:
      [@eventbrite.client, @eventbrite.mapper]

  eventbrite.events:
    class: %eventbrite.events_class%
    parent: eventbrite.abstract_repository

  eventbrite.organizers:
    class: %eventbrite.organizers_class%
    parent: eventbrite.abstract_repository

  eventbrite.venues:
    class: %eventbrite.venues_class%
    parent: eventbrite.abstract_repository

  eventbrite.users:
    class: %eventbrite.users_class%
    parent: eventbrite.abstract_repository
