parameters:
  eventbrite.client_class: Guzzle\Service\Client
  eventbrite.client_factory_class: SFBCN\EventbriteBundle\Eventbrite\ClientFactory
  eventbrite.base_url: "https://www.eventbrite.com/xml/"
  eventbrite.events_class: SFBCN\EventbriteBundle\Entity\EventRepository

services:
  eventbrite.client:
    class: %eventbrite.client_class%
    factory_class: %eventbrite.client_factory_class%
    factory_method: "factory"
    public: false
    arguments:
      [{ app_key: %app_key%, user_key: %user_key%, services_description_file: %services_description_file%, base_url: %eventbrite.base_url%}]

  eventbrite.events:
    class: %eventbrite.events_class%
    arguments:
      [@eventbrite.client]
