<?php
namespace SFBCN\EventbriteBundle\Tests\Form\Type;

use SFBCN\EventbriteBundle\Form\Type\VenueType;
use Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-17 at 07:29:19.
 */
class VenueTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \SFBCN\EventbriteBundle\Form\ChoiceList\VenueChoiceList
     */
    protected $venueChoiceList;

    /**
     * @var \SFBCN\EventbriteBundle\Form\DataTransformer\VenueToIdTransformer
     */
    protected $venueToIdTransformer;

    /**
     * @var VenueType
     */
    protected $object;

    /**
     * Set up the fixture
     */
    protected function setUp()
    {
        $this->venueChoiceList = m::mock('\SFBCN\EventbriteBundle\Form\ChoiceList\VenueChoiceList');
        $this->venueToIdTransformer = m::mock('SFBCN\EventbriteBundle\Form\DataTransformer\VenueToIdTransformer');

        $this->object = new VenueType($this->venueChoiceList, $this->venueToIdTransformer);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * @covers SFBCN\EventbriteBundle\Form\Type\VenueType::buildForm
     */
    public function testBuildForm()
    {
        $formBuilder = m::mock('Symfony\Component\Form\FormBuilder');
        $formBuilder->shouldReceive('add')->with('venue', 'choice', array('choice_list' => $this->venueChoiceList))->andReturn($formBuilder);
        $formBuilder->shouldReceive('appendClientTransformer')->with($this->venueToIdTransformer)->once();

        $this->assertNull($this->object->buildForm($formBuilder, array()));
    }

    /**
     * @covers SFBCN\EventbriteBundle\Form\Type\VenueType::buildView
     */
    public function testBuildView()
    {
        $view = m::mock('\Symfony\Component\Form\FormView');
        $view->shouldReceive('set')->with('widget', '#form-attributes#');

        $form = m::mock('\Symfony\Component\Form\Form');
        $form->shouldReceive('getAttribute')->with('widget')->once()->andReturn('#form-attributes#');

        $this->assertNull($this->object->buildView($view, $form));
    }

    /**
     * @covers SFBCN\EventbriteBundle\Form\Type\VenueType::getName
     */
    public function testGetName()
    {
        $this->assertEquals('venue', $this->object->getName());
    }
}
