<?php

namespace Tests\Eventbrite;

use SFBCN\EventbriteBundle\Eventbrite\ClientFactory;
use Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-30 at 23:17:52.
 */
class ClientFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ClientFactory
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * Test case for SFBCN\EventbriteBundle\Eventbrite\ClientFactory::factory
     *
     * @expectedException \Guzzle\Service\Exception\ValidationException
     */
    public function testFactoryMethodThrowsExceptionOnWrongParams()
    {
        ClientFactory::factory(array('test' => 'test'));
    }

    /**
     * Test case for SFBCN\EventbriteBundle\Eventbrite\ClientFactory::factory
     *
     * @covers SFBCN\EventbriteBundle\Eventbrite\ClientFactory::factory
     */
    public function testFactory()
    {
        $config = array(
            'app_key'                   => 'test',
            'user_key'                  => 'test',
            'servicesDescriptionFile'   => dirname(__DIR__) . '/../Resources/config/eventbrite.xml',
            'base_url'                  => 'https://www.eventbrite.com/xml'
        );

        $this->assertInstanceOf('\Guzzle\Service\Client', ClientFactory::factory($config));
    }
}
