<?php
namespace SFBCN\EventbriteBundle\Tests\Form\DataTransformer;

use Symfony\Component\Form\Exception\UnexpectedTypeException;

use SFBCN\EventbriteBundle\Form\DataTransformer\OrganizerToIdTransformer;
use SFBCN\EventbriteBundle\Entity\OrganizerRepository;
use Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-17 at 08:44:10.
 */
class OrganizerToIdTransformerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OrganizerToIdTransformer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * @expectedException \Symfony\Component\Form\Exception\UnexpectedTypeException
     */
    public function testTransformShouldThrowExceptionOnUnexpectedTypePassed()
    {
        $organizerRepository = m::mock('\SFBCN\EventbriteBundle\Entity\OrganizerRepository');
        $this->object = new OrganizerToIdTransformer($organizerRepository);

        $this->object->transform('test');
    }

    /**
     * @covers SFBCN\EventbriteBundle\Form\DataTransformer\OrganizerToIdTransformer::transform
     */
    public function testTransform()
    {
        $organizerRepository = m::mock('\SFBCN\EventbriteBundle\Entity\OrganizerRepository');
        $this->object = new OrganizerToIdTransformer($organizerRepository);

        $organizer = m::mock('\SFBCN\EventbriteBundle\Entity\Organizer');
        $organizer->shouldReceive('getId')->withNoArgs()->once()->andReturn(1);

        $this->assertEquals(1, $this->object->transform($organizer));
    }

    /**
     * @covers SFBCN\EventbriteBundle\Form\DataTransformer\OrganizerToIdTransformer::reverseTransform
     * @expectedException \Symfony\Component\Form\Exception\UnexpectedTypeException
     */
    public function testReverseTransformThrowsExceptionOnUnexpectedValuePassed()
    {
        $organizerRepository = m::mock('\SFBCN\EventbriteBundle\Entity\OrganizerRepository');
        $this->object = new OrganizerToIdTransformer($organizerRepository);

        $this->object->reverseTransform(array());
    }

    /**
     * @covers SFBCN\EventbriteBundle\Form\DataTransformer\VenueToIdTransformer::reverseTransform
     */
    public function testReverseTransform()
    {
        $organizerRepository = m::mock('\SFBCN\EventbriteBundle\Entity\OrganizerRepository');
        $organizerRepository->shouldReceive('findOrganizer')->with('1')->once()->andReturn('#organizer#');

        $this->object = new OrganizerToIdTransformer($organizerRepository);

        $this->assertEquals('#organizer#', $this->object->reverseTransform('1'));
    }
}
