<?php

namespace SFBCN\EventbriteBundle\Tests\Entity;

use SFBCN\EventbriteBundle\Entity\UserRepository;
use SFBCN\EventbriteBundle\Eventbrite\Mapper;
use Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 00:49:58.
 */
class UserRepositoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserRepository
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * @covers SFBCN\EventbriteBundle\Entity\UserRepository::findUser
     */
    public function testFindVenue()
    {
        $command = m::mock('\Guzzle\Service\Command\AbstractCommand');

        $response = simplexml_load_string(<<<EOX
<?xml version="1.0" encoding="UTF-8" ?>
<user><id>1</id></user>
EOX
        );

        $mapper = m::mock('\SFBCN\EventbriteBundle\Eventbrite\Mapper');
        $mapper->shouldReceive('map')->with($response)->once()->andReturn('#user#');

        $client = m::mock('stdClass');
        $client->shouldReceive('getCommand')->with('user.get', array())->once()->andReturn($command);
        $client->shouldReceive('execute')->with($command)->once()->andReturn($response);

        $this->object = new UserRepository($client, $mapper);
        $result = $this->object->findUser();

        $this->assertEquals('#user#', $result);
    }

    /**
     * @covers SFBCN\EventbriteBundle\Entity\UserRepository::getEvents
     * @todo   Implement testGetEvents().
     */
    public function testGetEvents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SFBCN\EventbriteBundle\Entity\UserRepository::getVenues
     * @todo   Implement testGetVenues().
     */
    public function testGetVenues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SFBCN\EventbriteBundle\Entity\UserRepository::getOrganizers
     * @todo   Implement testGetOrganizers().
     */
    public function testGetOrganizers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
